const actionTypes = {
  INCREASE_CART_PRODUCT_COUNT: 'INCREASE_CART_PRODUCT_COUNT',
  DECREASE_CART_PRODUCT_COUNT: 'DECREASE_CART_PRODUCT_COUNT',
  UPDATE_CART_PRODUCT_COUNT: 'UPDATE_CART_PRODUCT_COUNT',
  REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
  REMOVE_PRODUCTS_FROM_CART: 'REMOVE_PRODUCTS_FROM_CART',
  EMPTY_CART: 'EMPTY_CART',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  ADD_PRODUCT_TO_WISHLIST: 'ADD_PRODUCT_TO_WISHLIST',
  REMOVE_PRODUCT_FROM_WISHLIST: 'REMOVE_PRODUCT_FROM_WISHLIST',
  REMOVE_PRODUCTS_FROM_WISHLIST: 'REMOVE_PRODUCTS_FROM_WISHLIST',
};

export default actionTypes;
