const actionTypes = {
  INCREASE_PRODUCT_COUNT: 'INCREASE_PRODUCT_COUNT',
  DECREASE_PRODUCT_COUNT: 'DECREASE_PRODUCT_COUNT',
  UPDATE_PRODUCT_COUNT: 'UPDATE_PRODUCT_COUNT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  REMOVE_PRODUCTS: 'REMOVE_PRODUCTS',
  EMPTY_CART: 'EMPTY_CART',
  ADD_PRODUCT: 'ADD_PRODUCT',
};

export default actionTypes;
