const actionTypes = {
  SET_INVENTORY_STATUSES: 'SET_INVENTORY_STATUSES',
  SET_PRICE_CURRENCIES: 'SET_PRICE_CURRENCIES',
  SET_ACCOUNT_TYPES: 'SET_ACCOUNT_TYPES',
  SET_PRIVILEGES: 'SET_PRIVILEGES',
};

export default actionTypes;
